#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-remove" ]; then
    # Vendor logo alternative
    update-alternatives --install \
            /usr/share/images/vendor-logos \
            vendor-logos \
            /usr/share/images/radxa-logos 100
    # Desktop theme alternative
    update-alternatives --install \
            /usr/share/desktop-base/active-theme \
            desktop-theme \
            /usr/share/desktop-base/radxa-theme 100
fi

#DEBHELPER#

exit 0
