#!/bin/sh
set -e

#DEBHELPER#

case $1 in
    remove)
        conflicts="
        /etc/skel/.face
        /etc/xdg/kcm-about-distrorc
        /usr/share/sddm/themes/breeze/theme.conf
        "
        for i in $conflicts
        do
            dpkg-divert --package radxa-desktop-branding --rename --remove "$i"
        done
        ;;
esac

exit 0
