#!/bin/sh

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --remove \
            vendor-logos \
            /usr/share/images/radxa-logos
fi

#DEBHELPER#

exit 0
